### ISSUE TITLE
1.0 Release Plan

### ISSUE THREAD

**Issue by ben** [libgit2/libgit2#2136]
Must Do
-------

These are things without which we will not ship v1.0

- [ ] **Network** - See if we can unify the push and fetch refspec setting (why use a specific push function when you can already add the refspecs to the remote in-memory?) [#1125](https://github.com/libgit2/libgit2/issues/1125) is somewhat related.
- [x] **Network** - Coordinate with git-core about what `--tags` is supposed to mean (see current threads from mhagger)
- [x] **Network** - https://github.com/libgit2/libgit2/pull/1199
- [ ] **Submodules** - Fix bugs with using `.git/config` instead of `.gitmodules` and writing to `.git/modules/SM/config` when needed
- [ ] **Diff** - Add option for getting unmerged entries if index contains unmerged items

Optional
--------

These are things we would like to get to but will not block 1.0 being shipped

- [ ] **ODB** - Allow removal of objects from the odb (for backends that can).
- [ ] **Status** - Add conflict details to status.
- [x] **SSH** - Add support for accessing the hostkey; do something about ssh config. Maybe we should explicitly rely on libssh2 and give access to the underlying objects so the user can use libssh2 functions directly?
- [ ] [MAYBE] **Network** - Figure out if we want to support stuff like `remote.*.prune` which recently landed in git.
- [ ] [MAYBE] **Network** - Support for url replacements? (like `url.<base>.insteadOf`)
- [ ] [MAYBE] **Misc** - Support for looking up arbitrary commit header fields
- [ ] [MAYBE] **Diff** - Word diff
- [ ] [MAYBE] **Diff** - Histogram diff
- [ ] [MAYBE] **Diff** - Combined diff format. (I guess this one will involve API changes.)
- [ ] Support `http.<url>.sslVerify` in [remote.c: get_check_cert](https://github.com/libgit2/libgit2/blob/2d9291943c253e9e1520f87b13abb1e81cffdb29/src/remote.c#L105)

Code investigations
--------------------

- [ ] Why does `src/netops.c:gitno_connection_data_from_url()` discard the path which `gitno_extract_url_parts` gave it?

Done
----

These are things that started on this list but have been **D O N E** :sparkles:

- [x] **References** - Let's stop pretending that refs and the reflog are two different things. Change the refdb backend to know to update a ref and reflog atomically. See [#1920 comment](https://github.com/libgit2/libgit2/pull/1920#issuecomment-27409525)
- [x] **Network** - Always create `FETCH_HEAD` which we currently skip if there are no configured refspecs (we should download the remote's HEAD then and store it in `FETCH_HEAD`. We also seem to recreate the file for each refspec, when we should put in all of them. See [#1914](https://github.com/libgit2/libgit2/pull/1914)
- [x] **Network** - Better refspec list handling. Currently it's annoying and not all that useful. Do like jgit and use something like `set_refspecs(char *list[])`?  See [#1914](https://github.com/libgit2/libgit2/pull/1914)
- [x] **Network** - `git_remote_list()` is stupid. Return the list instead.
- [x] **References** - Get rid of `git_branch_foreach()`. It's already using the iterator interface, so if we do want it, let's just make it a multiplexing iterator. [#1938](https://github.com/libgit2/libgit2/pull/1938)
- [x] **Misc** - Have more sensible names for the streaming indexer functions, now that it's the only one we have. Remove `_stream_` everywhere, and probably rename `_add` to `_append`. `_finalize` should probably be named `_commit` or such. 'Finalize' has different meanings in OO languages. See [#1918](https://github.com/libgit2/libgit2/pull/1918)
- [x] **Network** - Support `multi_ack_detailed` and thin packs, as Google Code won't talk to us unless we do. See [#1919](https://github.com/libgit2/libgit2/pull/1919) for `multi_ack_detailed`.
- [x] **SSH** - More descriptive names for the functions and auth types instead of the confusing key+password vs key+own-crypto divide- [DONE] **Merge** - Ship it
- [x] **Blame** - Ship it
- [x] **Misc** - Correctly handle `core.precomposeunicode`, which is important for non-ASCII filenames on HFS+
- [x] **Revwalk** - It uses recursion to mark commits as uninteresting, which can blow the stack. See [#1223](https://github.com/libgit2/libgit2/issues/1223) and a proposed fix at [#1791](https://github.com/libgit2/libgit2/pull/1791)
- [x] **Config** - Support for config includes [#1833](https://github.com/libgit2/libgit2/pull/1833)
- [x] **Config** - The XDG/global tests are fragile and currently fail if the user running the tests has a config in the XDG location. These tests need to be isolated better.
- [x] **Network** - Have the indexer check what the hash for a packfile should be.
- [x] **Misc** - Ship some version of public filtering API
- [x] **Misc** - Check if we correctly ref-count the memory windows. See e.g. #1272
- [x] **Diff** - Patience diff
- [x] **Diff** - Minimal diff

**Comment by carlosmn** [comment]
I think it's safe to say we've thrown this plan right out the window so it's probably for the best to close it. We do absolutely want to release a stable version, focusing on an API we're ready to support for a long time, but that's not this issue.
