### ISSUE TITLE
support git 2.21's multi-pack-index

### ISSUE THREAD

**Issue by lhchavez** [libgit2/libgit2#5399]
Starting from version 2.21, git supports [`multi-pack-index`](https://github.blog/2019-02-24-highlights-from-git-2-21/#multi-pack-indexes), which allows for O(log _n_) scan of _n_ objects among _m_ packfiles (instead of O(_m_ log _n/m_)) without needing to do a garbage collection to compact all the objects into a single `.pack` file. This is desirable in cases where there are lots of [Delta islands](https://github.blog/2019-02-24-highlights-from-git-2-21/#delta-islands) or it is otherwise undesirable to merge large numbers of packfiles.

This should be relatively straightforward to implement. [`odb_pack.c`](https://github.com/libgit2/libgit2/blob/master/src/odb_pack.c) would need to be modified so that the `multi-pack-index`'s index is consulted first. Only if an OID is not found there, it should fall back to the current behavior of iterating over all the `.pack` files, although [`packfile_load__cb()`](https://github.com/libgit2/libgit2/blob/ee3307a183e39d602b25fa94831c6fc09e7c1b61/src/odb_pack.c#L197-L230) should be modified to ignore any files that are indexed in `multi-pack-index` (to avoid degenerating back into O(_m_ log _n/m_) complexity).

This can be split in four chunks for easier reviewing:

* [x] Support for parsing `multi-pack-index` files, and a fuzzer because parsing is hard. ~~#5401~~ merged
* [x] Support for reading existing `multi-pack-index` files. ~~#5403~~ merged
* [x] Support for creating a new `multi-pack-index` file from a set of `.pack` files. #5404
* [x] Support for creating / updating a `multi-pack-index` file from an open repository. #5405

Relevant documentation:

* https://github.com/git/git/blob/master/Documentation/technical/multi-pack-index.txt
* https://github.com/git/git/blob/master/Documentation/technical/pack-format.txt

**Comment by lhchavez** [comment]
Part 1 should be out for review within ~a week.

**Comment by pks-t** [comment]
Quick note so you don't feel ignored: I'll start reviewing your code as soon as we've released v1.0, which should be soonish. Looking forward to having multipack index support!

**Comment by sluongng** [comment]
what is the status for this issue?

I see active commits but I'm not quite sure regarding the progress.

@lhchavez do you need any help? should we split the issue/PRs into even smaller parts?

**Comment by lhchavez** [comment]
> what is the status for this issue?

i've been using this feature in production (from my branch) for months now.

> @lhchavez do you need any help? should we split the issue/PRs into even smaller parts?

i think it's as split into smaller parts as feasible / convenient (both for me and the reviewers)

**Comment by ethomson** [comment]
💥  Thanks for this!  So excited to see this shipping.
